"""add product contact lead

Revision ID: c7e79ae193c0
Revises: 
Create Date: 2026-04-25 17:08:45.424649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e79ae193c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_contact_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('client_phone', sa.String(length=30), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('product_summary_json', sa.Text(), nullable=False),
    sa.Column('estimated_total', sa.Integer(), nullable=False),
    sa.Column('whatsapp_phone', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='fk_product_contact_lead_shop_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_contact_lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_contact_lead_client_phone'), ['client_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_contact_lead_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_contact_lead_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_contact_lead_source'), ['source'], unique=False)

    with op.batch_alter_table('delivery_inquiry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_inquiry_city'))
        batch_op.drop_index(batch_op.f('ix_delivery_inquiry_created_at'))
        batch_op.drop_index(batch_op.f('ix_delivery_inquiry_phone'))

    op.drop_table('delivery_inquiry')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index('ix_activity_logs_category', ['category'], unique=False)
        batch_op.create_index('ix_activity_logs_level', ['level'], unique=False)
        batch_op.create_index('ix_activity_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('ix_activity_logs_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_activity_logs_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('commission_percent')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('vendor_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('ix_order_created_at_order_ip'))
        batch_op.drop_index(batch_op.f('ix_order_created_at_phone_digits'))
        batch_op.drop_index(batch_op.f('ix_order_created_at_status'))
        batch_op.drop_index(batch_op.f('ix_order_delivery_platform_fee_cents'))
        batch_op.create_index(batch_op.f('ix_order_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_guest_token'), ['guest_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_order_ip'), ['order_ip'], unique=False)
        batch_op.create_foreign_key('fk_order_courier_id_user', 'user', ['courier_id'], ['id'])
        batch_op.create_foreign_key('fk_order_assigned_by_user_id_user', 'user', ['assigned_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_order_baba_fee_settled_by_user_id_user', 'user', ['baba_fee_settled_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_order_period_id_order_period', 'order_period', ['period_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.alter_column('low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('vendor_subscription_monthly_cents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_vendor_id'), ['vendor_id'], unique=False)

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_closed_until'), ['closed_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_is_open'), ['is_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_vendor_id'), ['vendor_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_last_ts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_last_ts', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.VARCHAR(length=64), nullable=True))

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_shop_is_open'))
        batch_op.drop_index(batch_op.f('ix_shop_is_active'))
        batch_op.drop_index(batch_op.f('ix_shop_created_at'))
        batch_op.drop_index(batch_op.f('ix_shop_closed_until'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_product_shop_id'))
        batch_op.drop_index(batch_op.f('ix_product_kind'))
        batch_op.drop_index(batch_op.f('ix_product_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_created_at'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))

    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.alter_column('vendor_subscription_monthly_cents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_period_id_order_period', type_='foreignkey')
        batch_op.drop_constraint('fk_order_baba_fee_settled_by_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_order_assigned_by_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_order_courier_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_order_ip'))
        batch_op.drop_index(batch_op.f('ix_order_guest_token'))
        batch_op.drop_index(batch_op.f('ix_order_delivered_at'))
        batch_op.create_index(batch_op.f('ix_order_delivery_platform_fee_cents'), ['delivery_platform_fee_cents'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_at_status'), ['created_at', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_at_phone_digits'), ['created_at', 'phone_digits'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_at_order_ip'), ['created_at', 'order_ip'], unique=False)
        batch_op.alter_column('vendor_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_percent', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_logs_user_id')
        batch_op.drop_index('ix_activity_logs_timestamp')
        batch_op.drop_index('ix_activity_logs_resource')
        batch_op.drop_index('ix_activity_logs_level')
        batch_op.drop_index('ix_activity_logs_category')

    op.create_table('delivery_inquiry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('price_cents', sa.INTEGER(), nullable=False),
    sa.Column('item_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pickup_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dropoff_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('note_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('urgent', sa.BOOLEAN(), nullable=False),
    sa.Column('desired_datetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_inquiry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_inquiry_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_inquiry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_inquiry_city'), ['city'], unique=False)

    with op.batch_alter_table('product_contact_lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_contact_lead_source'))
        batch_op.drop_index(batch_op.f('ix_product_contact_lead_shop_id'))
        batch_op.drop_index(batch_op.f('ix_product_contact_lead_created_at'))
        batch_op.drop_index(batch_op.f('ix_product_contact_lead_client_phone'))

    op.drop_table('product_contact_lead')
    # ### end Alembic commands ###
